2025-03-11 11:23:11,334,18 INFO - üöÄ Migration process initiated at 2025-03-11 11:23:11. - [main.py:10 - main()]
2025-03-11 11:23:11,334,18 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:20 - main()]
2025-03-11 11:23:11,334,18 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 16, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:21 - main()]
2025-03-11 11:23:11,334,18 INFO - ‚úÖ Migration completed in 0.00 seconds at 2025-03-11 11:23:11.
________________________________________________________________________________ - [main.py:26 - main()]
2025-03-11 11:40:45,962,19 INFO - üöÄ Migration process initiated at 1 started at 2025-03-11 11:40:45. - [main.py:11 - main()]
2025-03-11 11:40:46,000,19 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:22 - main()]
2025-03-11 11:40:46,001,19 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:23 - main()]
2025-03-11 11:40:46,001,19 INFO - ‚úÖ Migration completed 1 finished at 2025-03-11 11:40:46 after 0.038597 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 11:41:09,730,20 INFO - üöÄ Migration process initiated at 1 started at 2025-03-11 11:41:09. - [main.py:11 - main()]
2025-03-11 11:41:09,731,20 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:22 - main()]
2025-03-11 11:41:09,731,20 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:23 - main()]
2025-03-11 11:41:09,731,20 INFO - ‚úÖ Migration completed 1 finished at 2025-03-11 11:41:09 after 0.000594 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 11:41:53,927,21 INFO - üöÄ Migration process initiated at 1 started at 2025-03-11 11:41:53. - [main.py:11 - main()]
2025-03-11 11:41:53,927,21 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 11:41:53,927,21 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 11:41:53,927,21 INFO - ‚úÖ Migration completed 1 finished at 2025-03-11 11:41:53 after 0.000620 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 11:42:21,923,22 INFO - üöÄ Migration process initiated at 1 started at 2025-03-11 11:42:21. - [main.py:11 - main()]
2025-03-11 11:42:21,923,22 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 11:42:21,924,22 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 11:42:21,934,22 INFO - ‚úÖ Migration completed 1 finished at 2025-03-11 11:42:21 after 0.010476 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 12:29:46,634,23 INFO - üöÄ Migration process initiated at #1 started at 2025-03-11 12:29:46. - [main.py:11 - main()]
2025-03-11 12:29:46,634,23 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 12:29:46,634,23 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 12:29:46,634,23 INFO - ‚úÖ Migration completed #1 finished at 2025-03-11 12:29:46 after 0.000376 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 12:30:27,385,24 INFO - üöÄ Migration process initiated at Benchmark#1 started at 2025-03-11 12:30:27. - [main.py:11 - main()]
2025-03-11 12:30:27,385,24 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 12:30:27,385,24 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 12:30:27,385,24 INFO - ‚úÖ Migration completed Benchmark#1 finished at 2025-03-11 12:30:27 after 0.000473 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 12:31:05,373,25 INFO - üöÄ Migration process initiated, Benchmark#1 started at 2025-03-11 12:31:05. - [main.py:11 - main()]
2025-03-11 12:31:05,373,25 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 12:31:05,373,25 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 12:31:05,373,25 INFO - ‚úÖ Migration completed Benchmark#1 finished at 2025-03-11 12:31:05 after 0.000380 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 12:31:49,325,26 INFO - üöÄ Migration process initiated, benchmark#1 started at 2025-03-11 12:31:49. - [main.py:11 - main()]
2025-03-11 12:31:49,325,26 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 12:31:49,325,26 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 12:31:49,325,26 INFO - ‚úÖ Migration completed benchmark#1 finished at 2025-03-11 12:31:49 after 0.000379 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 12:44:18,867,27 INFO - üöÄ Migration process initiated, benchmark#1 started at 2025-03-11 12:44:18. - [main.py:11 - main()]
2025-03-11 12:44:18,867,27 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 12:44:18,867,27 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 12:44:18,867,27 INFO - ‚úÖ Migration completed benchmark#1 finished at 2025-03-11 12:44:18 after 0.000401 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
2025-03-11 12:44:29,841,33 INFO - üöÄ Migration process initiated, benchmark#1 started at 2025-03-11 12:44:29. - [main.py:11 - main()]
2025-03-11 12:44:29,841,33 ERROR - ‚ùå Something went wrong: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping' - [main.py:21 - main()]
2025-03-11 12:44:29,841,33 ERROR - ‚ùå Detailed error: Traceback (most recent call last):
  File "/app/main.py", line 17, in main
    Bank()
  File "/app/migrations/bank.py", line 31, in Bank
    migrator = Migrator()
TypeError: Migrator.__init__() missing 3 required positional arguments: 'source_table', 'destination_table', and 'column_mapping'
 - [main.py:22 - main()]
2025-03-11 12:44:29,841,33 INFO - ‚úÖ Migration completed benchmark#1 finished at 2025-03-11 12:44:29 after 0.000441 seconds.
________________________________________________________________________________ - [main.py:28 - main()]
